/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 rocket-final.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/rocket-final.glb')
  const { actions } = useAnimations(animations, group)
  
}

useGLTF.preload('/rocket-final.glb')
