/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 rocket2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/rocket2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="14618_Human_Brain_Bookend_v1" position={[-0.144, -0.033, -0.222]} rotation={[Math.PI / 2, 0, 0.972]}>
          <mesh name="14618_Human_Brain_Bookend_v1_1" geometry={nodes['14618_Human_Brain_Bookend_v1_1'].geometry} material={materials['Material.006']} />
          <mesh name="14618_Human_Brain_Bookend_v1_2" geometry={nodes['14618_Human_Brain_Bookend_v1_2'].geometry} material={materials['Material.007']} />
          <mesh name="14618_Human_Brain_Bookend_v1_3" geometry={nodes['14618_Human_Brain_Bookend_v1_3'].geometry} material={materials['Material.008']} />
        </group>
        <mesh name="controls001" geometry={nodes.controls001.geometry} material={materials.Space_ship_phone_and_speed_control} position={[0.468, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="Icosphere" position={[0.15, -0.028, -0.236]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Icosphere_1" geometry={nodes.Icosphere_1.geometry} material={materials.towers} />
          <mesh name="Icosphere_2" geometry={nodes.Icosphere_2.geometry} material={materials.water} />
          <mesh name="Icosphere_3" geometry={nodes.Icosphere_3.geometry} material={materials.land} />
        </group>
        <group name="interior" position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="interior_1" geometry={nodes.interior_1.geometry} material={materials.Space_ship_interior_base} />
          <mesh name="interior_2" geometry={nodes.interior_2.geometry} material={materials['Material.001']} />
        </group>
        <mesh name="objects" geometry={nodes.objects.geometry} material={materials.Space_ship_chair_screens_lamps} position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="objects001" geometry={nodes.objects001.geometry} material={materials.Space_ship_interior_base} position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
        <group name="Sphere" position={[-0.013, -0.022, -0.281]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Sphere_1" geometry={nodes.Sphere_1.geometry} material={materials.Space_ship_phone_and_speed_control} />
          <mesh name="Sphere_2" geometry={nodes.Sphere_2.geometry} material={materials.fb} />
          <mesh name="Sphere_3" geometry={nodes.Sphere_3.geometry} material={materials.globe} />
          <mesh name="Sphere_4" geometry={nodes.Sphere_4.geometry} material={materials.reddit} />
          <mesh name="Sphere_5" geometry={nodes.Sphere_5.geometry} material={materials.discord} />
          <mesh name="Sphere_6" geometry={nodes.Sphere_6.geometry} material={materials.ig} />
          <mesh name="Sphere_7" geometry={nodes.Sphere_7.geometry} material={materials['Material.002']} />
          <mesh name="Sphere_8" geometry={nodes.Sphere_8.geometry} material={materials['Material.003']} />
          <mesh name="Sphere_9" geometry={nodes.Sphere_9.geometry} material={materials['Material.004']} />
          <mesh name="Sphere_10" geometry={nodes.Sphere_10.geometry} material={materials['Material.005']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rocket2.glb')
