/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 rocket.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rocket.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['14618_Human_Brain_Bookend_v1'].geometry} material={materials.Space_ship_phone_and_speed_control} position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.controls.geometry} material={materials.Space_ship_phone_and_speed_control} position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.controls001.geometry} material={materials.Space_ship_phone_and_speed_control} position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials.Space_ship_phone_and_speed_control} position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.interior_1.geometry} material={materials.Space_ship_interior_base} />
        <mesh geometry={nodes.interior_2.geometry} material={materials.Space_ship} />
      </group>
      <mesh geometry={nodes.objects.geometry} material={materials.Space_ship_chair_screens_lamps} position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.objects001.geometry} material={materials.Space_ship_chair_screens_lamps} position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.Space_ship_phone_and_speed_control} position={[0, -1.17, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/rocket.glb')
