/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Scene1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Scene1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="wewnatrz_do_sfabaobjcleanergles" />
        <group name="Astronaut" position={[-9.8, 4.592, -2.134]} rotation={[-1.461, 0.192, 1.047]} scale={2.082}>
          <primitive object={nodes._rootJoint} />
          <group name="Object_9">
            <skinnedMesh name="Astronaut_Astronaut_0" geometry={nodes.Astronaut_Astronaut_0.geometry} material={materials.Astronaut} skeleton={nodes.Astronaut_Astronaut_0.skeleton} />
            <skinnedMesh name="Astronaut_Astronaut_0_1" geometry={nodes.Astronaut_Astronaut_0_1.geometry} material={materials['Material.002']} skeleton={nodes.Astronaut_Astronaut_0_1.skeleton} />
          </group>
        </group>
        <group name="Object_2" position={[-9.848, 6.005, -13.364]} rotation={[-1.808, 0.019, -1.961]} scale={0.006}>
          <mesh name="Object_0" geometry={nodes.Object_0.geometry} material={materials.Space_ship} />
          <mesh name="Object_0_1" geometry={nodes.Object_0_1.geometry} material={materials.Material} />
          <mesh name="Object_0_2" geometry={nodes.Object_0_2.geometry} material={materials['Material.001']} />
        </group>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} scale={20.333} />
        <mesh name="Dave" geometry={nodes.Dave.geometry} material={materials['Material.005']} position={[15.279, 1.103, 17.973]} rotation={[Math.PI / 2, 0, -0.733]} scale={0.598} />
        <mesh name="Description" geometry={nodes.Description.geometry} material={materials['Material.005']} position={[15.198, 0.899, 18.004]} rotation={[Math.PI / 2, 0, -0.733]} scale={0.157} />
        <group name="Bubbletext" position={[16.895, -1.228, 15.339]} rotation={[0.736, 0.562, -0.234]} scale={0.093}>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.003']} />
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Material.004']} />
        </group>
      </group>a
    </group>
  )
}

useGLTF.preload('/Scene1.glb')
